const axios = require('axios');

/**
 * Summarize YouTube subtitles using OpenAI GPT.
 * @param {string} transcript - The video transcript to summarize.
 * @param {string} model - The GPT model to use (e.g., 'gpt-3.5-turbo').
 * @returns {Promise<string>} - The summary generated by GPT.
 */
async function youtubeTranscribeWithGPT(transcript, model = 'gpt-3.5-turbo') {
    const prompt = `
Summarize the following YouTube video transcript in a concise and informative way:
---
${transcript}
---
    `;

    try {
        const response = await axios.post(
            'https://api.openai.com/v1/chat/completions',
            {
                model,
                messages: [{ role: 'user', content: prompt }],
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
                },
            }
        );

        const summary = response.data.choices[0]?.message?.content?.trim();
        if (!summary) {
            throw new Error('No summary returned from OpenAI.');
        }

        return summary;
    } catch (err) {
        console.error('Error communicating with OpenAI:', err.message);
        throw new Error('Failed to summarize using OpenAI.');
    }
}

module.exports = youtubeTranscribeWithGPT;
